// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"encoding/json"
)

type JobScraperLinkedinGeoLocation struct {
	ID       []byte
	Location string
	GeoID    string
	State    string
	Country  string
}

type JobScraperUser struct {
	ID        []byte
	Name      string
	Email     string
	Location  json.RawMessage
	Keywords  json.RawMessage
	Cookie    sql.NullString
	CsrfToken sql.NullString
	CreatedAt sql.NullTime
}
