// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
	"encoding/json"
)

type JobScraperLinkedinGeoLocation struct {
	ID       []byte
	Location string
	GeoID    string
	State    string
	Country  string
}

type JobScraperUser struct {
	ID        []byte
	Name      string
	Email     sql.NullString
	Location  json.RawMessage
	Keywords  json.RawMessage
	Cookie    string
	CsrfToken string
	CreatedAt sql.NullTime
}
